# Generated by Django 5.2.10 on 2026-02-14 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('specialty', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('experience', models.IntegerField(help_text='Years of experience')),
                ('medical_council_no', models.CharField(max_length=50, unique=True)),
                ('license_document', models.FileField(upload_to='doctor_licenses/')),
                ('clinic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('clinic_address', models.TextField(blank=True, null=True)),
                ('clinic_city', models.CharField(blank=True, max_length=100, null=True)),
                ('clinic_state', models.CharField(blank=True, max_length=100, null=True)),
                ('clinic_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Doctors.doctor')),
            ],
            options={
                'ordering': ['day', 'time_from'],
                'unique_together': {('doctor', 'day')},
            },
        ),
    ]
